version: '3.8'

services:
  backend:
    build: ./
    container_name: mon-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./views
    container_name: mon-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
